### ISSUE TITLE
Add comments, what to achieve with the new commits

### ISSUE THREAD

**Issue by rubo77** [ffnord/alfred#1]
Please add some comments why you implemented these: 
# add debian/ directory

Wilfried Klaebe committed on 27 Sep
# use some values passed in via environment

Wilfried Klaebe committed on 27 Sep

**Comment by wklaebe** [comment]
debian/ directory was added to be able to build a debian package directly from the repo

using values passed in from the environment effectively to enable building without further patching while not changing default behaviour
